### ISSUE TITLE
Can Gendle Glow work on TabUltraC?

### ISSUE THREAD

**Issue by llinfeng** [calin-darie/gentle-glow-onyx-boox#19]
The color e-ink devices for now need extra strong backlight to undo its darker white background color. For now, unuder Version 3.3, Gentle Glow doesn't seem to be able to adjust Brightness nor Warmth on TablUltraC. It works well on other Boox tablets with firmware 3.3.2 (Lumi 2, Tab X and Tab Ultra).

When I try to toggle the Frontligiht button in the upper right corner, Gentle Glow crashes.
![image](https://github.com/calin-darie/gentle-glow-onyx-boox/assets/5890407/a50343bb-e72f-4410-a437-d95d1e8f31bb)

**Comment by llinfeng** [comment]
Hi, thanks for letting me know about the update. On both Tab C and Tab mini C, under firmware v3.4, gentle-glow v4.0 can launch properly, but toggling between the presets and sliding the sliders didn't do anything. Now, clicking Gentle Glow icon in the Control Center no longer generates the crash prompt, though.

I assume something fundamental has changed on Boox devices in the Ultra and Tab lines, that they have a slider for brightness and a slider for adjusting the mixture of warm and white backlight.

Here is how the Frontlight section looks like on Tab C:
![image](https://github.com/calin-darie/gentle-glow-onyx-boox/assets/5890407/be1d3b2a-2713-4425-8ff9-fd4eb895dbbf)

**Comment by calin-darie** [comment]
Thanks for the updates! Fixed in 4.3. Closing for now. Please reopen if needed

**Comment by llinfeng** [comment]
@calin-darie Thank you for updating. I tested v4.4, and it worked great on Tab C.

**Comment by llinfeng** [comment]
Minor note on the v4.4 installer - it won't install properly on a table with existing gentle-glow installations - needed to uninstall the existing older versions (3.4, 4.0 and 4.1) first. (I was installing the updated gentle-glow apk on Tab Mini C, Tab C, Tab Ultra and Tab X).
