### ISSUE TITLE
Broken in the boox 3.4 beta firmware with build number 2023-08-02_19-54_3.4

### ISSUE THREAD

**Issue by mncfre** [calin-darie/gentle-glow-onyx-boox#21]
Hi, I love this app, but something changes in the boox 3.4 beta firmware with build number 2023-08-02_19-54_3.4 on my tab ultra because Gentle Glow doesn't work anymore, it opens but selecting or modifying the profiles don't do anything, it just keeps the front light setting from the standard sliders.

**Comment by mncfre** [comment]
> Hi! I've updated the Books libraries, and made a minor adjustment based on buggy behavior on NoteAir2.
> 
> 
> 
> But I'm not in the beta program, so can you please let me know if v4.0 works correctly for you now?

Thanks a lot, I update to 4.0 but it still don't work on 3.4 beta, I notice that boox change the light sliders so maybe they updated their APIs

**Comment by mncfre** [comment]
With the latest with the 4.1 update it still don't work on the 3.4 beta firmware on my TU

**Comment by calin-darie** [comment]
Thanks for keeping me posted! Fixed in 4.3. Closing for now. Please reopen if needed
