### ISSUE TITLE
Adapt UI for portrait layout on 2:1 aspect devices such a Boox Palma

### ISSUE THREAD

**Issue by CrazyCoder** [calin-darie/gentle-glow-onyx-boox#22]
At the moment, the "Saved" status changes the height of the dialog when the text is wrapped, and when it disappears on slider drag, the height is changed again. This is causing dialog size changes before/after dragging the sliders, and "Saved" looks ugly while wrapped.

The dialog can also utilize the full screen width for the sliders to be longer to allow more easier/precise dragging.

![image](https://github.com/calin-darie/gentle-glow-onyx-boox/assets/122834/6026de7d-8b9f-4afd-bf60-59996c3f2c67)

**Comment by calin-darie** [comment]
Fixed in v4.4 Just realized that the Replace with preset... button takes a lot of screen estate for very little actual use. Replaced it with a revert icon ↩ + tooltip for all form factors

Also reduced the horizontal padding of the dialog just for the Normal ones. Not sure if Poke is also affected.
