### ISSUE TITLE
Add On/Off button

### ISSUE THREAD

**Issue by mergen3107** [calin-darie/gentle-glow-onyx-boox#9]
Hi!

Thank you very much for this great app!
I use it with Button Mapper, having Gentle Glow open upon long-press of the physical Back button on my Onyx Boox Kon-Tiki 2 (it has the same platform as Nova 3).

Can you please add the lights On/Off button into the dialog itself? Currently I can only switch the lights on/off via Notifications Quick Settings for Gentle Glow, or with Onyx stock window, which requires additional steps.

Thank you!

**Comment by calin-darie** [comment]
Hi!
Thanks for the suggestion!
I'll surely find a way to enable turning off the light from the dialog. 
I was about to suggest that you create an "off" setting, with 0 brightness. But as I was testing that, I noticed it's broken: if you select the "off" setting and close the dialog, then when you open the dialog again  the light is turned on to a different setting than before, which is kinda annoying.

**Comment by mergen3107** [comment]
Thank you!

Yes, I tried this one and wondered why it doesn't stick

**Comment by calin-darie** [comment]
I will add a toggle button in the top right corner. This is consistent with other features accessible from the quick settings, e.g. wifi and bluetooth. 
Whenever you open the dialog, the toggle will be automatically turned on. 
When you turn the toggle off, the setting radiobuttons and brightness&warmth sliders will be invisible. 

A second step will disable brightness-0 settings, and replace them with the default presets for people who had set them before. If we were to have off profiles, the whole warmth slider is useless, the `lights on at dialog open` rule would conflict with the `restore the latest setting` rule. 

- [x]  spec ready for first development
- [x]  technical tasks defined
- [ ]  first app store release
- [ ]  tested and approved in app store

**Comment by calin-darie** [comment]
@mergen3107 v3.0 is out with a slightly new layout, to accomodate the on/off button. You can no longer set the brightness to 0 from the slider or decrease button. 

Can you please let me know if it all works fine for you?

**Comment by mergen3107** [comment]
@calin-darie 
Thank you! I’ll test it in a while once I have more time
